// frontends/member-portal/src/HelpButton.tsx
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { useTranslation } from "react-i18next";

/** A "?" trigger that opens a localized, keyboard-dismissable help dialog. */
export function HelpButton() {
  const { t } = useTranslation();
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open]);

  return (
    <>
      <button type="button" className="help-trigger" aria-label={t("help.open")} onClick={() => setOpen(true)}>
        ?
      </button>
      {open &&
        createPortal(
          <div className="help-overlay" onClick={() => setOpen(false)}>
            <div
              className="help-dialog"
              role="dialog"
              aria-modal="true"
              aria-label={t("help.title")}
              onClick={(e) => e.stopPropagation()}
            >
              <h2>{t("help.title")}</h2>
              <section>
                <h3>{t("help.pointsHeading")}</h3>
                <p>{t("help.pointsBody")}</p>
              </section>
              <section>
                <h3>{t("help.tiersHeading")}</h3>
                <p>{t("help.tiersBody")}</p>
              </section>
              <section>
                <h3>{t("help.rewardsHeading")}</h3>
                <p>{t("help.rewardsBody")}</p>
              </section>
              <button type="button" className="help-close" autoFocus onClick={() => setOpen(false)}>
                {t("help.close")}
              </button>
            </div>
          </div>,
          document.body,
        )}
    </>
  );
}

// frontends/admin-portal/src/components/HelpButton.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";

const open = ref(false);

function onKey(e: KeyboardEvent) {
  if (e.key === "Escape") open.value = false;
}
onMounted(() => window.addEventListener("keydown", onKey));
onUnmounted(() => window.removeEventListener("keydown", onKey));
</script>

<template>
  <button type="button" class="help-trigger" :aria-label="$t('help.open')" @click="open = true">?</button>
  <!-- Teleport to body so the fixed overlay escapes the header's stacking context and sits above content. -->
  <Teleport to="body">
    <div v-if="open" class="help-overlay" @click="open = false">
      <div class="help-dialog" role="dialog" aria-modal="true" :aria-label="$t('help.title')" @click.stop>
        <h2>{{ $t("help.title") }}</h2>
        <section><h3>{{ $t("help.lookupHeading") }}</h3><p>{{ $t("help.lookupBody") }}</p></section>
        <section><h3>{{ $t("help.adjustHeading") }}</h3><p>{{ $t("help.adjustBody") }}</p></section>
        <section><h3>{{ $t("help.pandionHeading") }}</h3><p>{{ $t("help.pandionBody") }}</p></section>
        <section><h3>{{ $t("help.ratesHeading") }}</h3><p>{{ $t("help.ratesBody") }}</p></section>
        <button type="button" class="help-close" @click="open = false">{{ $t("help.close") }}</button>
      </div>
    </div>
  </Teleport>
</template>
